# ! MVL Datasets
datasets:
  mvl_root_challenge: /media/public_dataset/mvl_challenge
  mvl_root: /media/public_dataset/mvl_dataset
  zind_root: /media/public_dataset/ZInD/360_layout_challenge

  hm3d_mvl:
    dataset_name: hm3d_mvl
    img_dir: ${datasets.mvl_root_challenge}/mvl_challenge_dataset/img
    geometry_info_dir: ${datasets.mvl_root}/hm3d_mvl/geometry_info
    # labels_dir: ${datasets.mvl_root}/hm3d_mvl/labels/phi_coords
    labels_dir: ${datasets.mvl_root_challenge}/mvl_challenge_dataset/labels/gt
    test_scene_list: ${datasets.mvl_root}/hm3d_mvl/scene_lists/scene_list__testing_set.json
    train_scene_list: ${datasets.mvl_root}/hm3d_mvl/scene_lists/scene_list__training_set.json
    resolution: [512, 1024]

  mp3d_fpe_mvl: 
    dataset_name: mp3d_fpe_mvl
    img_dir: ${datasets.mvl_root_challenge}/mvl_challenge_dataset/img
    geometry_info_dir: ${datasets.mvl_root}/mp3d_fpe/geometry_info
    # labels_dir: ${datasets.mvl_root}/mp3d_fpe/labels/phi_coords
    labels_dir: ${datasets.mvl_root_challenge}/mvl_challenge_dataset/labels/gt
    test_scene_list: ${datasets.mvl_root}/mp3d_fpe/scene_lists/scene_list__testing_set.json
    train_scene_list: ${datasets.mvl_root}/mp3d_fpe/scene_lists/scene_list__training_set.json

    resolution: [512, 1024]

  zind_mvl:
    dataset_name: zind_mvl
    img_dir: ${datasets.zind_root}/img
    geometry_info_dir: ${datasets.zind_root}/geometry_info
    labels_dir: ${datasets.zind_root}/labels/layout_raw
    test_scene_list: ${datasets.zind_root}/scene_lists/scene_list__testing_set.json
    train_scene_list: ${datasets.zind_root}/scene_lists/scene_list__training_set.json
    resolution: [512, 1024]

