
experiment_name: ${date}
log_dir: ${oc.env:LY_MODELS_ASSETS}/${script}/${experiment_name}
script: ${hydra:job.name}

hydra:
  run:
    dir: ${log_dir}

# dirname: ${get_hydra_dirname:}

date: ${now:%y%m%d}
time: ${now:%H%M%S}