trained_models: ${load:${oc.env:LY_MODELS_CFG}/trained_models.yaml}

ExponentialLR:
  name: ExponentialLR
  lr_decay_rate: 0.90

weighted_L1:
  min_std: 0.001

Adam_optimizer: 
    name: Adam
    lr: 0.00005
    beta1: 0.9
    weight_decay: 0.0
  
model:
  device: cuda:${model.cuda}
  cuda: 0
  ly_model: HorizonNetV2
  ckpt: ${trained_models.mp3d.ckpt}  
  seed: 594277
  cfg_train:
    epochs: 10
    save_ckpt: True
    device: ${model.device}
    seed: ${model.seed}
    batch_size: 16
    size: -1
    num_workers: 4
    optimizer: ${Adam_optimizer}
    scheduler: ${ExponentialLR}
    bn_momentum: 0
    freeze_earlier_blocks: -1
    save_every: -1
  cfg_valid:
    device: ${model.device}
    seed: ${model.seed}
    batch_size: 16
    size: -1
    num_workers: 4
  cfg_inference:
    device: ${model.device}
    seed: ${model.seed}
    batch_size: 16
    size: -1
    num_workers: 4

