

PROJECT_VER: testing_new_hn


train_dataset: ${datasets.hm3d_mvl}

valid_dataset: 
  img_dir: ${mvl_root_challenge}/mvl_challenge_dataset/img
  geometry_info_dir: ${mvl_root}/hm3d_mvl/geometry_info
  labels_dir: ${mvl_root}/hm3d_mvl/labels/phi_coords
  scene_list: ${mvl_root}/hm3d_mvl/scene_lists/scene_list__testing_set.json
  resolution: [512, 1024]


trail: 0
cuda: 0

model:
  seed: ${trail}
  cuda: ${cuda}
  ckpt: ${trained_models.mp3d.ckpt}  
  cfg_train:
    epochs: 10
    data: ${train_dataset}
    batch_size: 4
    num_workers: 4
    save_ckpt: True
  cfg_valid:
    data: ${valid_dataset}
    batch_size: 16
    num_workers: 4
  cfg_inference:
    data: ${infer_dataset}
    batch_size: 16
    num_workers: 4
  

defaults:
  - general
  - datasets
  - horizon_net_new
  - _self_
  
log_dir: ${get_hydra_file_dirname:}/logs/${date}

hydra:
  searchpath:
    - ${oc.env:LY_MODELS_CFG}

  
